jobs:
  postman-tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: |
          docker compose -f docker-compose.test.yml up -d --build
          docker compose -f docker-compose.test.yml ps

      - name: Wait for API to be healthy
        run: |
          echo "Waiting for API..."
          until curl --silent http://localhost:8000/finance/cycles/; do
            sleep 5
          done

      - name: Install Node.js and Newman
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run tests/postman/collections/Finance\ API.postman_collection.json \
          -e tests/postman/collections/DEV.postman_environment.json \
          --reporters cli,junit \
          --reporter-junit-export results.xml \
          --suppress-exit-code

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: postman-results
          path: results.xml

      - name: Tear down services
        run: docker compose -f docker-compose.test.yml down -v
