# Generated by Django 5.1.3 on 2025-02-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
