name: Run Postman Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start Postgres service
        run: docker compose up -d db

      - name: Wait for Postgres to be healthy
        run: |
          echo "Waiting for Postgres..."
          for i in {1..10}; do
            docker compose exec db pg_isready -U postgres && break
            sleep 3
          done

      - name: Build and start Django service
        run: docker compose up -d gradiafinance

      - name: Wait for Django server to be ready
        run: |
          echo "Waiting for Django..."
          for i in {1..15}; do
            docker-compose exec gradiafinance curl --retry 5 --retry-delay 3 http://localhost:8000/finance/cycles/ && break
            echo "Retry $i..."
            sleep 3
          done

      - name: Run Postman Collection inside Django container
        run: |
          docker-compose exec gradiafinance newman run tests/postman/collections/Finance\ API.postman_collection.json \
          -e tests/postman/collections/DEV.postman_environment.json \
          --reporters cli,junit \
          --reporter-junit-export /app/results.xml \
          --suppress-exit-code

      - name: Copy results from container
        run: docker cp $(docker-compose ps -q gradiafinance):/app/results.xml ./results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: postman-results
          path: results.xml
